#!/bin/bash

# sync yaml and html
python sync_html.py

git config user.name "Heekang Park"
git config user.email "park.heekang33@gmail.com"

git add .

time=`date '+%F %H:%M'`
commit_msg="api docs update, $time"

if [ -n "$1" ]; then
    commit_msg=$1
fi

git commit -m "$commit_msg"

git push origin master